###############################################################################
#               PHP/Angular Dev environment with reverse proxy                #
###############################################################################
version: '3'

networks:
 novanet:
  driver: bridge

services:

    # Proxyserver for multihost use
    proxy:
     image: nginx:1.16-alpine
     volumes:
      - ./docker-files/proxy/proxy.conf:/etc/nginx/conf.d/proxy.conf
     restart: always
     ports:
      - 80:80
     networks:
      - novanet

    # Database management tool
    adminer:
     image: adminer
     restart: always
     ports:
      - 8002:8080
     networks:
      - novanet

    # Database
    db:
     image: postgres:11.3-alpine
     restart: always
     working_dir: /application
     volumes:
      - .:/application
      - ./docker-storage/postgres:/var/lib/postgresql/data
     environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=appdb
     ports:
      - 8001:5432
     networks:
      - novanet

    # Webserver of the project
    webserver:
      image: nginx:1.16-alpine
      restart: always
      working_dir: /application
      volumes:
          - ./projects-backend:/application
          - ./projects-frontend:/angular-applications
          - ./docker-files/webserver/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - 8080:80
      networks:
       - novanet

    # Webserver PHP-Gateway of the project
    php-fpm:
      build: docker-files/webserver
      restart: always
      volumes:
        - ./projects-backend:/application
        - ./docker-files/webserver/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
      networks:
       - novanet

    # Frontend app
    node-angular:
     build: docker-files/nodeangular
     restart: always
     working_dir: /angular-applications
     volumes:
      - ./projects-frontend:/angular-applications
     ports:
      - 4200:4200
      - 4201:4201
     networks:
      - novanet

    # Minio High Performance Object Storage
    minio:
     image: minio/minio
     restart: always
     ports:
      - 9001:9000
     volumes:
      - ./docker-storage/minio:/data
     environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: pass1234
     command: server /data
     networks:
      - novanet

volumes:
 docker-storage: