##############################
#     Official Node Image    #
##############################

FROM node:12.16.0

# Set working directory
WORKDIR /angular-applications

# Install Angular CLI
RUN npm install -g @angular/cli@9.0.3

CMD tail -f /dev/null
